# Generated by Django 5.0.6 on 2024-07-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_date_of_birth_remove_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=32),
        ),
    ]
