# Generated by Django 5.0.6 on 2024-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_delete_category_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
