# Generated by Django 5.0.6 on 2024-06-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_thread_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
