# Generated by Django 5.0.6 on 2024-07-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_forum_slug_alter_thread_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3BB143', max_length=7)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='forum',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
