# Generated by Django 5.0.6 on 2024-07-01 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_threadprefix_alter_forum_slug_alter_thread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.threadprefix'),
        ),
    ]
