# Generated by Django 5.0.6 on 2024-07-03 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_thread_prefix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AlterModelOptions(
            name='threadprefix',
            options={'verbose_name_plural': 'thread prefixes'},
        ),
        migrations.AlterField(
            model_name='thread',
            name='prefix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='main.threadprefix'),
        ),
        migrations.AlterField(
            model_name='threadprefix',
            name='color',
            field=models.CharField(default='#2386CC', max_length=7),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='forum',
            table='forum',
        ),
        migrations.AlterModelTable(
            name='thread',
            table='thread',
        ),
        migrations.AlterModelTable(
            name='threadprefix',
            table='thread_prefix',
        ),
    ]
